In [74]:
import numpy as np


lst_temp = [4,1,0,-2,5,7,-3,0,0,5,0,-1,3,6,9,5,7,11,9,6,0];
arr_temp = np.array(lst_temp);

print(arr_temp[arr_temp<0].size)
print(arr_temp.argmax());
print(np.any(arr_temp>10));
print(np.any(arr_temp>20));
print(np.all(arr_temp<10));
print(arr_temp[arr_temp<0]);
print(np.sort(arr_temp));

3
17
True
False
False
[-2 -3 -1]
[-3 -2 -1  0  0  0  0  0  1  3  4  5  5  5  6  6  7  7  9  9 11]


In [80]:
v1 = np.array([3, 7]);
v2 = np.array([2, 2]);

print(v1 + v2);
print(v1 * 2);
print(v1 - v2);
print(np.dot(v1, v2));
print(np.linalg.norm(v1));
print(np.linalg.norm(v1 - v2));
print(np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2)));
print(v1.shape);

[5 9]
[ 6 14]
[1 5]
20
7.615773105863909
5.0990195135927845
0.9284766908852592
(2,)


In [92]:
mtrx = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(mtrx);
print('-------');
print(mtrx[2,:]);
print('-------');
mtrx2 = np.array([2, 3, 4]);
print(mtrx + mtrx2);
print('-------');
print(np.dot(mtrx, mtrx2));
print('-------');
print(mtrx.T)
print('-------');
print(mtrx.T.T == mtrx)
print('-------');
print(np.linalg.det(mtrx));
print('-------');
print(np.linalg.inv(mtrx));
print('-------');
print(np.linalg.matrix_rank(mtrx));
print('-------');


[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------
[7 8 9]
-------
[[ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]
-------
[20 47 74]
-------
[[1 4 7]
 [2 5 8]
 [3 6 9]]
-------
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
-------
-9.51619735392994e-16
-------
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
-------
2
-------


In [93]:
a = np.array([[1,5],[2,3]])
b = np.array([11,8])
x = np.linalg.solve(a,b)
print(x)
print(np.dot(a, x))

[1. 2.]
[11.  8.]
